### ISSUE TITLE
CSS vars

### ISSUE THREAD

**Issue by Luchanso** [alfa-laboratory/alfa-ui-primitives#121]
Было бы здорово вынести все цвета в css переменные, чтобы можно было использовать их в .css стилях, как это сейчас сделано в arui-feather:
```css
@import 'arui-feather/vars.css';

.my-example {
  color: var(--color-accent-content-minor)
}
```
